growingio/growingio-sdk-ios-autotracker

Growing/GrowingIO/GrowingTracker/Public/GrowingTracker.m, scripts/build.sh
进入该脚本所在目录下，执行 sh build.sh -cv 0.1.0 -av 0.1.1 即可
=> chore(build.sh): 修改打包脚本

Example/Example/APITests/GIOClickEventViewController.m, Example/Example/UICategoryTests/PageStructure/GIOMultiViewController.m, GrowingAutoTracker/GrowingIMPTrack/GrowingIMPTrack.m, GrowingAutoTracker/GrowingNode/UIAlertController+GrowingNode.m, GrowingAutoTracker/GrowingNode/UIView+GrowingNode.m, GrowingAutoTracker/Page/GrowingPageManager.m, GrowingAutoTracker/Page/UIViewController+GrowingPageHelper.m, GrowingAutoTracker/Public/GrowingAutoTracker.h, GrowingAutoTracker/Public/GrowingConfiguration+GrowingAutoTrack.m, GrowingTracker/Event/GrowingDeviceInfo.m, GrowingTracker/Event/GrowingEventManager.m, GrowingTracker/GrowingGlobal.h, GrowingTracker/GrowingGlobal.m, GrowingTracker/Public/GrowingConfiguration.m
修复一些bug
1. 视图和页面忽略策略定义不明确
2. impressionScale 不生效，完善定义逻辑
3. 修复 deviceId 的keychain
4. 其他优化
=> Optimization bugfix

GrowingAutoTracker/GrowingNode/GrowingNodeHelper.m, GrowingAutoTracker/WebCircle/GrowingWebCircle.m, GrowingTracker/Event/GrowingPageEvent/GrowingPageEvent.m, GrowingTracker/Event/GrowingVisitEvent.m, README.md
1. 圈选间隔为 200ms，仅响应 click以及page事件，click点击会造成view视图改变
2. 添加visit请求的networkState字段，同时去除Page事件的该字段。
=> 修改圈选发送间隔，fix缺少和多余的networkState字段

Example/Example/Base.lproj/Main.storyboard
=> fix: 修改 demo 进入 AttributeLabel 页面crash 问题

GrowingAutotrackerCore/Event/GrowingViewElementEvent.m, GrowingAutotrackerCore/Hybrid/GrowingHybridBridgeProvider.m, GrowingAutotrackerCore/Manager/GrowingViewControllerLifecycle.m, GrowingAutotrackerCore/WebCircle/GrowingWebCircle.m, GrowingAutotrackerCore/WebCircle/GrowingWebCircleElement.m, GrowingTrackerCore/Event/GrowingEventGenerator.m, GrowingTrackerCore/Hook/GrowingAppLifecycle.m, GrowingTrackerCore/NetWork/Request/GrowingEventRequest.m, GrowingTrackerCore/NetWork/Request/GrowingNetworkConfig.h
1. 修改window筛选逻辑，查找keywindow后再查找顶层window，并过滤GrowingWindow
2. 修正网络url地址
3. 修正数据协议字段，index = -1，字段不再添加
=> fix: 修改window筛选逻辑

GrowingAutotrackerCore/WebCircle/GrowingWebCircle.m, GrowingTrackerCore/DeepLink/GrowingWebWatcher.h, GrowingTrackerCore/DeepLink/GrowingWebWatcher.m, GrowingTrackerCore/GrowingRealTracker.m
通过growing.530c8231345c492d://?openConsoleLog=Yes测试
=> feat: 增加urlscheme打开debug

Example/Example.xcodeproj/project.pbxproj, Example/ExampleTests/OtherTests/HybridTests.m, GrowingAnalytics.podspec, GrowingTrackerCore/DeepLink/MobileDebugger/GrowingMobileDebugger.h, GrowingTrackerCore/DeepLink/MobileDebugger/GrowingMobileDebugger.m, GrowingTrackerCore/NetWork/Request/GrowingNetworkConfig.h, GrowingTrackerCore/NetWork/Request/GrowingNetworkConfig.m, Podfile.lock
1. 修改数据有可能遍历时会进行添加操作问题
2. 发布 3.1.0-beta 版本
=> fix: 防止数组遍历时增删操作，发布3.1.0-beta版本

GrowingTrackerCore/DeepLink/MobileDebugger/GrowingMobileDebugger.m
=> fix: 修改头文件导入

GrowingAutotrackerCore/Page/GrowingPageGroup.h, GrowingAutotrackerCore/Page/GrowingPageGroup.m, GrowingAutotrackerCore/Page/GrowingPageManager.m
=> fix: pageGroup的初始化问题以及childpages变更为弱引用

GrowingAutotrackerCore/Impression/GrowingImpressionTrack.m, GrowingTrackerCore/DeepLink/MobileDebugger/GrowingMobileDebugger.m, GrowingTrackerCore/Event/GrowingEventDataBase.m
将导致应用后台到前台时，imp 半自动浏览事件未采集
以及：
1. EventManager 相关代码拼写纠错
2. Mobile Debugger 无用的拦截器代码去除
=> fix: imp track 备份数据源未初始化

GrowingTrackerCore/DataBase/GrowingEventDataBase.h, GrowingTrackerCore/DataBase/GrowingEventDataBase.m, GrowingTrackerCore/Event/GrowingEventManager.h, GrowingTrackerCore/Event/GrowingEventManager.m
=> refactor: Event Database 重构

Example/Example.xcodeproj/project.pbxproj, Example/Example/GrowingIO-Info.plist, Example/ExampleTests/OtherTests/HybridTests.m, GrowingAnalytics.podspec, GrowingAutotrackerCore/GrowingRealAutotracker.m, GrowingTrackerCore/Core/GrowingModuleManager.h, GrowingTrackerCore/Core/GrowingModuleManager.m, GrowingTrackerCore/Core/GrowingModuleProtocol.h, GrowingTrackerCore/Core/Protocols/GrowingRequestProtocol.h, GrowingTrackerCore/Event/GrowingEventChannel.h, GrowingTrackerCore/Event/GrowingEventChannel.m, GrowingTrackerCore/Event/GrowingEventManager.h, GrowingTrackerCore/Event/GrowingEventManager.m, GrowingTrackerCore/GrowingRealTracker.m, GrowingTrackerCore/GrowingTrackConfiguration.h, GrowingTrackerCore/GrowingTrackConfiguration.m, GrowingTrackerCore/NetWork/Request/GrowingEventRequest.h, GrowingTrackerCore/NetWork/Request/GrowingEventRequest.m, Modules/MobileDebugger/GrowingMobileDebugger.m, Podfile, Podfile.lock
同时修改Module在dyld链接阶段就会初始化问题，移至SDK初始化时进行同步初始化Module
=> feat: 广告sdk功能添加

Example/Example/AppDelegate.m, GrowingAutotrackerCore/GrowingAutotrackConfiguration.m, GrowingTrackerCore/Event/Base/GrowingBaseEvent.m, GrowingTrackerCore/Event/GrowingEventFilter.h, GrowingTrackerCore/Event/GrowingEventFilter.m, GrowingTrackerCore/Event/GrowingEventManager.m, GrowingTrackerCore/Event/GrowingFieldsIgnore.h, GrowingTrackerCore/Event/GrowingFieldsIgnore.m, GrowingTrackerCore/Event/Tools/GrowingPersistenceDataProvider.h, GrowingTrackerCore/GrowingRealTracker.m, GrowingTrackerCore/GrowingTrackConfiguration.h, GrowingTrackerCore/GrowingTrackConfiguration.m, Podfile.lock
=> add: 增加事件过滤接口

GrowingTrackerCore/Event/GrowingEventManager.h, GrowingTrackerCore/Event/GrowingEventManager.m, GrowingTrackerCore/GrowingRealTracker.m
1. ApplicationDidEnterBackground 触发一次 flush
2. 优化 GrowingEventManager 代码结构，删除无用代码
=> fix: App 退到后台 flush 一次，避免 Page 事件丢失

Example/Example/AppDelegate.m, Example/ExampleTests/ManualTrackTest/CS1ManualTrackTest.m, GrowingTrackerCore/Event/Base/GrowingBaseEvent.m, GrowingTrackerCore/GrowingTrackConfiguration.h, GrowingTrackerCore/GrowingTrackConfiguration.m, GrowingTrackerCore/Manager/GrowingSession.m
新增 Id Mapping 开关`idMappingEnabled`，默认为 NO；
关闭情况下，设置多用户身份 userKey 无效；
=> feat: 新增 Id Mapping 开关

CHANGELOG.md, GrowingAnalytics.podspec
=> feat: release 3.3.1 正式版

.github/workflows/cocoapods.yml, .github/workflows/cocoapods_beta.yml, .github/workflows/cocoapods_beta_manual.yml
仅修改action的workflow机制，用于测试需要
无
无
无
=> ci: action添加cocoapods beta的手动发布workflow

GrowingAutotrackerCore/Autotrack/NSNotificationCenter+GrowingAutotracker.m, GrowingAutotrackerCore/Autotrack/UIAlertController+GrowingAutotracker.h, GrowingAutotrackerCore/Autotrack/UIAlertController+GrowingAutotracker.m, GrowingAutotrackerCore/Autotrack/UICollectionView+GrowingAutotracker.m, GrowingAutotrackerCore/Autotrack/UISegmentedControl+GrowingAutotracker.h, GrowingAutotrackerCore/Autotrack/UISegmentedControl+GrowingAutotracker.m, GrowingAutotrackerCore/Autotrack/UITableView+GrowingAutotracker.m, GrowingAutotrackerCore/Autotrack/UIViewController+GrowingAutotracker.h, GrowingAutotrackerCore/Autotrack/UIViewController+GrowingAutotracker.m, GrowingAutotrackerCore/GrowingNode/Category/UIAlertController+GrowingNode.m, GrowingAutotrackerCore/GrowingNode/Category/UISegmentedControl+GrowingNode.m, GrowingAutotrackerCore/GrowingNode/Category/UIView+GrowingNode.m, GrowingAutotrackerCore/GrowingNode/GrowingNodeHelper.h, GrowingAutotrackerCore/GrowingNode/GrowingNodeHelper.m, GrowingTrackerCore/Core/GrowingModuleManager.m, GrowingTrackerCore/DeepLink/GrowingAppDelegateAutotracker.m, GrowingTrackerCore/Event/Base/GrowingBaseEvent.h, GrowingTrackerCore/Event/GrowingDataTraffic.m, GrowingTrackerCore/Event/GrowingEventChannel.h, GrowingTrackerCore/Event/Tools/GrowingPersistenceDataProvider.h, GrowingTrackerCore/Event/Tools/GrowingPersistenceDataProvider.m, GrowingTrackerCore/FileStorage/GrowingFileStorage.m, GrowingTrackerCore/GrowingSwizzle/GrowingSwizzler.m, GrowingTrackerCore/Helpers/NSArray+GrowingHelper.m, GrowingTrackerCore/Helpers/NSDictionary+GrowingHelper.m, GrowingTrackerCore/Helpers/NSObject+GrowingIvarHelper.m
修复 sonarCloud 中 Major 级别以上质量检测 Bug，以及部分 Minor 级别 Bug
- 增加必要的非空判断
- 增加`nullable`、`nonnull`限定符
无
无
无
=> fix: sonar reliability issues

Example/ExampleTests/OtherTests/HybridTests.m, GrowingAnalytics.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, GrowingTrackerCore/Core/GrowingModuleManager.m, GrowingTrackerCore/Event/Base/GrowingBaseEvent.h, GrowingTrackerCore/Event/Tools/GrowingPersistenceDataProvider.m, GrowingTrackerCore/GrowingSwizzle/GrowingSwizzler.m, GrowingTrackerCore/Helpers/NSString+GrowingHelper.m, GrowingTrackerCore/Helpers/NSURL+GrowingHelper.m, GrowingTrackerCore/Helpers/UIView+GrowingHelper.m, GrowingTrackerCore/Helpers/UIWindow+GrowingHelper.m, GrowingTrackerCore/NetWork/GrowingNetworkInterfaceManager.m, GrowingTrackerCore/Thirdparty/GrowingLogger/GrowingLog.m, GrowingTrackerCore/Thirdparty/GrowingLogger/GrowingTTYLogger.h, Modules/Hybrid/GrowingWebViewJavascriptBridgeConfiguration.m, Modules/MobileDebugger/GrowingMobileDebugger.m, Modules/WebCircle/GrowingWebCircle.m, Podfile, Podfile.lock
添加非空判断
kGrowingSpecialCharactersString = @ "_!@#$%^&*()-=+| \[]{},.<>/?" ->kGrowingSpecialCharactersString = @ "_!@#$%^&*()-=+| \\[]{},.<>/?"
无
无
无
=> fix: sonar quality optimization

GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m
3.3.1-hotfix.3 发布一周后，发布3.3.2正式版本
无
无
无
=> feat: 3.3.2正式版发布

Example/ExampleTests/Helper/MockEventQueue.h, Example/ExampleTests/Helper/MockEventQueue.m, Example/ExampleTests/ManualTrackTest/A4VisitorAttributesEventsTest.m, Example/ExampleTests/ManualTrackTest/CS1ManualTrackTest.m, Example/ExampleTests/ManualTrackTest/ConversionVariablesEventsTest.m, Example/ExampleTests/ManualTrackTest/CustomEventsTest.m, Example/ExampleTests/ManualTrackTest/LoginUserAttributerEventsTest.m, Example/ExampleTests/ManualTrackTest/PageAttributesEventsTest.m, Example/ExampleTests/OtherTests/WebSocketTests.m, Example/ExampleTests/ProtocolAndApi/A3VisitEventsTest.m
修改部分测试用例无法通过问题，改变MockEventQueue处理线程，除去UI操作外，避免使用waitForTimeInterval
单元测试全部通过即可
无
无
=> test: 修改部分测试用例无法通过问题，改变MockEventQueue处理线程

GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m, README.md
- 发布3.3.3-beta版本
- [feat: 数据存储与发送新增 Protobuf 格式](https://github.com/growingio/growingio-sdk-ios-autotracker/pull/177)
无
无
无
=> feat: release 3.3.3-beta

GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m
3.3.3 正式版发布
- [fix: 给 Web 端增加设置和清除 UserKey 的接口](https://github.com/growingio/growingio-sdk-ios-autotracker/pull/176)（ID Mapping）
- [feat: 数据存储与发送新增 Protobuf 格式](https://github.com/growingio/growingio-sdk-ios-autotracker/pull/177)
无
无
无
=> feat: release 3.3.3 正式版

Example/ExampleTests/OtherTests/HybridTests.m, GrowingAutotrackerCore/Autotrack/NSNotificationCenter+GrowingAutotracker.m, GrowingAutotrackerCore/Autotrack/UIAlertController+GrowingAutotracker.m, GrowingAutotrackerCore/Autotrack/UISegmentedControl+GrowingAutotracker.m, GrowingAutotrackerCore/Autotrack/UITapGestureRecognizer+GrowingAutotracker.h, GrowingAutotrackerCore/Autotrack/UITapGestureRecognizer+GrowingAutotracker.m, GrowingAutotrackerCore/Autotrack/UIViewController+GrowingAutotracker.m, GrowingAutotrackerCore/GrowingNode/Category/UICollectionView+GrowingNode.h, GrowingAutotrackerCore/GrowingNode/Category/UIControl+GrowingNode.h, GrowingAutotrackerCore/GrowingNode/Category/UIView+GrowingNode.m, GrowingAutotrackerCore/GrowingNode/Category/UIWindow+GrowingNode.h, GrowingTrackerCore/Helpers/NSDictionary+GrowingHelper.h, GrowingTrackerCore/Helpers/NSDictionary+GrowingHelper.m, GrowingTrackerCore/Helpers/NSString+GrowingHelper.h, GrowingTrackerCore/Helpers/NSString+GrowingHelper.m, GrowingTrackerCore/NetWork/Request/GrowingEventRequest.m, GrowingTrackerCore/NetWork/Request/GrowingLoginRequest.m, GrowingTrackerCore/NetWork/Request/GrowingNetworkConfig.m, Modules/Hybrid/GrowingHybridBridgeProvider.m, Modules/MobileDebugger/GrowingDebuggerEventQueue.h, Services/Network/GrowingNetworkManager.m, Services/Network/GrowingURLSessionProtocol.h, Services/Network/NSURLSession+GrowingURLSessionHelper.h, Services/Network/NSURLSession+GrowingURLSessionHelper.m
fix: Category 方法、C 函数、头文件中 Block 定义添加前缀，避免符号冲突
运行 Demo，正常上报数据
SDK 内部方法定义与调用
无
=> fix: Category 方法、C 函数、头文件中 Block 定义添加前缀，避免符号冲突

GrowingTrackerCore/Core/GrowingModuleManager.m, GrowingTrackerCore/Event/Autotrack/GrowingPageEvent.m, GrowingTrackerCore/FileStorage/GrowingFileStorage.m, GrowingTrackerCore/GrowingSwizzle/GrowingSwizzler.m, GrowingTrackerCore/Manager/GrowingConfigurationManager.h, GrowingTrackerCore/Manager/GrowingConfigurationManager.m, GrowingTrackerCore/Manager/GrowingStatusBarEventManager.m, GrowingTrackerCore/Menu/GrowingAlert.m, GrowingTrackerCore/Thread/GrowingThread.m, GrowingTrackerCore/Utils/GrowingArgumentChecker.m, GrowingTrackerCore/Utils/GrowingDynamicProxy.m, Modules/Hybrid/GrowingWebViewJavascriptBridgeConfiguration.m, Modules/Protobuf/Events/GrowingBaseAttributesEvent+Protobuf.m, Modules/Protobuf/Events/GrowingConversionVariableEvent+Protobuf.m, Modules/Protobuf/Events/GrowingViewElementEvent+Protobuf.m, Modules/Protobuf/Events/GrowingVisitEvent+Protobuf.m, Modules/Protobuf/Events/Hybrid/GrowingHybridViewElementEvent+Protobuf.m, Modules/Protobuf/Proto/GrowingPBEventV3Dto+GrowingHelper.h, Modules/Protobuf/Proto/GrowingPBEventV3Dto+GrowingHelper.m
fix: 修改 unregisterModule 时数组没有更新问题
fix: 删除无用代码，代码规范调整
fix: EventName Check 先判断 NSString 类型，再调用 NSString 分类方法判断是否为空
fix: -[NSProxy methodSignatureForSelector:] crash
fix: protobuf 不支持 Map 中含 NSNull Value
fix: protobuf eventType 判断应使用 isEqualToString
正常运行 Demo，单元测试通过
未修改前，部分应用场景和测试场景下，SDK 可能出现异常或崩溃
无
=> fix: some bugs fix

CHANGELOG.md, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec, GrowingAnalytics/GrowingTrackerCore/GrowingRealTracker.m
feat: release 3.3.4
CI 通过
新版本发布
无
=> feat: release 3.3.4

GrowingAnalytics/GrowingTrackerCore/Thirdparty/GrowingLogger/GrowingLog.m
fix: 日志输出添加前缀，方便搜索
运行 Demo，查看 SDK 日志输出是否有 **[GrowingAnalytics]** 前缀
- SDK 日志输出
无
=> fix: 日志输出添加前缀

CHANGELOG.md
=> docs: CHANGELOG 格式调整

CHANGELOG.md, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m, Podfile.lock
feat: release 3.3.6
- CI 通过
- 3.3.6 发版
无
=> feat: release 3.3.6

CHANGELOG.md, Example/Example/AppDelegate.m, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m
feat: release [3.4.0](https://github.com/growingio/growingio-sdk-ios-autotracker/compare/3.3.6...3.4.0)
- CI 通过
无
无
=> feat: release 3.4.0

CHANGELOG.md, Example/GrowingAnalyticsTests/ModulesTests/GA3AdapterTests/GA3AdapterTest.m, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec
- feat: release 3.4.1
- test: GA 3 Adapter 补充测试用例
- CI 通过
无
无
=> feat: release 3.4.1

GrowingTrackerCore/Utils/GrowingDeviceInfo.m
- fix: iOS 13 ApplicationState 在收到 UIScene 相关通知时并未转换
SDK 在 iOS 13 以上且使用了 UIScene 的情景下，注册了 UIScene 相关通知以获取 ApplicationState；
当收到 UISceneWillDeactivateNotification / UISceneDidActivateNotification 时，系统并未设定当前的 ApplicationState 为 Inactive / Active，导致此时获取到的值是不正确的</br>
处理方式：延后取值
- 使用 ExampleiOS13 进行测试前后台采集字段 `appState` 是否正确
- CI 通过
无
无
=> fix: iOS 13 ApplicationState 在收到 UIScene 相关通知时并未转换

GrowingAutotracker-cdp/GrowingAutotracker.h, GrowingAutotracker/GrowingAutotracker.h, GrowingTracker-cdp/GrowingTracker.h, GrowingTracker/GrowingTracker.h
- feat: 废弃 WithAttributesBuilder 相关接口
- CI 通过
WithAttributesBuilder 相关接口
无
=> feat: 废弃 WithAttributesBuilder 相关接口

CHANGELOG.md, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m
- feat: release 3.4.3
- CI 通过
无
无
=> feat: release 3.4.3

.github/workflows/SonarCloud.yml, .github/workflows/ci.yml, .github/workflows/cocoapods.yml, .github/workflows/cocoapods_beta.yml, .github/workflows/cocoapods_beta_manual.yml
- ci: actions/checkout、actions/cache update to v3
- ci: force Xcode 13.4.1
2022.10.19 起，CI 一直超时失败，查日志确认是 WebKit 崩溃导致，部分日志如下：
```
2022-10-20T02:24:14.1280740Z Test Case '-[HybridTest testGrowingHybridBridgeProvider]' started.
2022-10-20T02:24:14.1281400Z 2022-10-20 02:24:13.785927+0000 xctest[12497:33851] GIOLog#[GrowingAnalytics] handleJavascriptBridgeMessage: testHibrid
2022-10-20T02:24:14.1282130Z 2022-10-20 02:24:13.786525+0000 xctest[12497:33852] GIOLog#[GrowingAnalytics] handleJavascriptBridgeMessage: {@'messageType':@'messagedata'}
2022-10-20T02:24:14.1282860Z 2022-10-20 02:24:13.931528+0000 xctest[12497:32406] [ProcessSuspension] endowmentsForHandle: Process with PID 12497 is not running
2022-10-20T02:24:14.1284120Z 2022-10-20 02:24:13.934279+0000 xctest[12497:32406] [Process] …
```
=> ci: actions/checkout、actions/cache update to v3

CHANGELOG.md, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m
- feat: release 3.4.4
- CI 通过
- SDK 3.4.4 发版
无
=> feat: release 3.4.4

CHANGELOG.md, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m
- feat: release 3.4.5
- CI 通过
- SDK 3.4.5 发版
无
=> feat: release 3.4.5

CHANGELOG.md, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m
* feat: release 3.4.6
* CI 通过
* SDK 3.4.6 发版
无
=> feat: release 3.4.6

Example/GrowingAnalyticsTests/A0GrowingAnalyticsCDPTest.m, Example/GrowingAnalyticsTests/A0GrowingAnalyticsTest.m, GrowingTrackerCore/Timer/GrowingEventTimer.m, Modules/APM/GrowingAPMModule.m, Podfile.lock
* feat: rename apm/track_timer attributes keys
* 对应事件预置 key 是否已修改
* CI 通过
* APM/Track Timer 功能
无
=> feat: rename apm/track_timer attributes keys

CHANGELOG.md, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m
- feat: release 3.4.7
- CI 通过
- SDK 3.4.7 发版
无
=> feat: release 3.4.7

GrowingAutotracker-cdp/GrowingAutotracker.h
- CDP GrowingAutotracker 接口添加页面属性
- SDK 3.4.7 重发版
- CI 通过
- SDK 3.4.7
无
=> fix: UIViewController add growingPageAttributes api

Example/GrowingAnalyticsTests/GrowingAnalyticsStartTests/GrowingAnalyticsStartTests.m, GrowingTrackerCore/GrowingTrackConfiguration.m, GrowingTrackerCore/Network/Request/GrowingNetworkConfig.h, GrowingTrackerCore/Network/Request/GrowingNetworkConfig.m
* fix: default server host change to napi prefix
* CI 通过
* default server host
无
=> fix: default server host change to napi prefix

GrowingAutotrackerCore/Page/GrowingPageGroup.m, GrowingTrackerCore/Database/GrowingEventDatabase.m, GrowingTrackerCore/DeepLink/GrowingDeepLinkHandler.m, GrowingTrackerCore/Event/GrowingDataTraffic.m, GrowingTrackerCore/Event/Tools/GrowingPersistenceDataProvider.m, GrowingTrackerCore/Manager/GrowingApplicationEventManager.m, GrowingTrackerCore/Manager/GrowingSession.m, GrowingTrackerCore/Utils/GrowingDeviceInfo.m, GrowingTrackerCore/Utils/GrowingInternalMacros.h, Modules/Advert/Utils/GrowingAdUtils.m, Modules/MobileDebugger/GrowingDebuggerEventQueue.m, Modules/MobileDebugger/GrowingMobileDebugger.m, Modules/WebCircle/GrowingWebCircle.m, Services/WebSocket/GrowingSRWebSocket.m
* fix: priority inversion issue in GrowingSRWebSocket by Xcode14
* perf: replace dispatch_semaphore_t with os_unfair_lock
=> fix: priority inversion issue in GrowingSRWebSocket by Xcode14

GrowingTrackerCore/Network/GrowingNetworkInterfaceManager.h, GrowingTrackerCore/Network/GrowingNetworkInterfaceManager.m
同 #261，其用来发 hotfix，不合并；这个 PR 同步到 master 分支
=> fix: CTTelephonyNetworkInfo 偶现崩溃

.github/workflows/code_format.yml, Example/GrowingAnalyticsTests/A0GrowingAnalyticsCDPTest.m, Example/GrowingAnalyticsTests/TrackerCoreTests/CoreTests/GrowingModuleTest.m, Example/GrowingAnalyticsTests/TrackerCoreTests/CoreTests/GrowingServiceTest.m, GrowingTrackerCore/Core/GrowingContext.h, GrowingTrackerCore/Core/GrowingContext.m, GrowingTrackerCore/Core/GrowingModuleManager.m, GrowingTrackerCore/Core/GrowingServiceManager.m, GrowingTrackerCore/GrowingRealTracker.m, GrowingTrackerCore/Public/GrowingAnnotationCore.h, GrowingTrackerCore/Public/GrowingBaseService.h, GrowingTrackerCore/Public/GrowingModuleManager.h, GrowingTrackerCore/Public/GrowingModuleProtocol.h, GrowingTrackerCore/Public/GrowingServiceManager.h
模块化相关代码借鉴自 [alibaba/BeeHive](https://github.com/alibaba/BeeHive)，当时做了部分删减以适配 SDK 的需求；
但还有很多代码冗余，此 PR 进行了彻底删除和优化
=> refactor: 模块化代码优化

.github/workflows/code_format.yml, Podfile.lock
解决 CI 卡住不更新 status
`Expected — Waiting for status to be reported`
=> build: update ci

Example/Podfile, Package.swift
* chore: update apm module to version 0.0.15
=> feat: release 3.7.0

Example/GrowingAnalyticsTests/TrackerCoreTests/SwizzleTests/GrowingSwizzleTest.m, Example/Podfile.lock, GrowingAnalytics.podspec, GrowingAutotrackerCore/Autotrack/UICollectionView+GrowingAutotracker.m, GrowingAutotrackerCore/Autotrack/UITableView+GrowingAutotracker.m, Package.swift
* 见：#278，目前使用 [RSSwizzle](https://github.com/rabovik/RSSwizzle) 解决
=> fix: swizzle bug 

Example/Podfile.lock, GrowingAnalytics.podspec, GrowingAutotrackerCore/GrowingNode/GrowingNodeHelper.m, GrowingAutotrackerCore/GrowingNode/GrowingViewNode.m, GrowingTrackerCore/GrowingRealTracker.m, scripts/cocoapods-beta.sh, scripts/update_version.sh
* 在列表元素下的子元素 xcontent，其父级列表元素的位置应为通配 `-`
* 嵌套列表，则距子元素最近列表元素的位置为 `-`，其父级列表元素位置为具体 index
=> fix: xcontent in list

Example/GrowingAnalytics.xcworkspace/xcshareddata/IDETemplateMacros.plist, Example/GrowingAnalyticsTests/ServicesTests/ScreenshotTests/ScreenshotTest.m, Example/Podfile, Example/Podfile.lock, GrowingAnalytics.podspec, GrowingAutotrackerCore/Page/GrowingPageManager.m, GrowingTrackerCore/Event/Autotrack/GrowingViewElementEvent.m, GrowingTrackerCore/Event/Base/GrowingBaseEvent.m, GrowingTrackerCore/GrowingRealTracker.m, GrowingTrackerCore/Public/GrowingScreenshotService.h, Modules/Flutter/GrowingFlutterPlugin.h, Modules/Flutter/GrowingFlutterPlugin.m, Modules/MobileDebugger/GrowingMobileDebugger.m, Modules/WebCircle/GrowingWebCircle.m, Package.swift, Services/Screenshot/GrowingScreenshotProvider.m
* feat: flutter module to v4 logic
* fix: avoid duplicate codes with using GrowingUtils 1.1.0
* style: typo
* chore: update copyright
=> feat: flutter module to v4 logic

.github/workflows/ci.yml, .github/workflows/cocoapods.yml, .github/workflows/cocoapods_beta.yml, .github/workflows/cocoapods_beta_manual.yml, .github/workflows/code_format.yml, .github/workflows/draft_release_with_tag.yml, .github/workflows/draft_release_without_tag.yml, .github/workflows/spm.yml
=> ci: set pipefail output

Example/GrowingAnalyticsTests/GrowingAnalyticsStartTests/GrowingAnalyticsStartTests.m, Example/GrowingAnalyticsTests/GrowingAnalyticsStartTests/GrowingAnalyticsStartTests2.m, Example/GrowingAnalyticsTests/ModulesTests/ProtobufTests/ProtobufDatabaseTest.m, Example/GrowingAnalyticsTests/ServicesTests/DatabaseTests/JSONDatabaseTest.m, GrowingTrackerCore/Database/GrowingEventDatabase.m, GrowingTrackerCore/GrowingTrackConfiguration.m, GrowingTrackerCore/Public/GrowingEventDatabaseService.h, GrowingTrackerCore/Public/GrowingTrackConfiguration.h, Services/Database/GrowingEventFMDatabase.m
添加初始化配置项 dataValidityPeriod，类型 NSUInteger，范围 [3, 30]
修改本机时间进行测试
=> feat: data validity period

Example/Podfile.lock, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m
版本改动：https://github.com/growingio/growingio-sdk-ios-autotracker/commit/cd7f2e0ff253108b3ff08fef169e662c229356bb
=> feat: release 3.8.2

Example/Podfile.lock, GrowingAnalytics-cdp.podspec, GrowingAnalytics.podspec, GrowingTrackerCore/GrowingRealTracker.m, Modules/MobileDebugger/GrowingMobileDebugger.m
=> feat: release 3.8.4

Modules/Flutter/GrowingFlutterPlugin.m, Modules/MobileDebugger/GrowingMobileDebugger.m, Services/Database/FMDB/GrowingFMDatabase.m, Services/Database/FMDB/GrowingFMDatabaseAdditions.m, Services/Database/FMDB/GrowingFMDatabasePool.m, Services/Database/FMDB/GrowingFMDatabaseQueue.m, Services/Database/FMDB/GrowingFMResultSet.m, Services/WebSocket/GrowingSRWebSocket.m
See: https://github.com/growingio/growingio-sdk-ios-autotracker/releases/tag/3.8.3
=> fix: 同步 v3.8.3 上的修改内容

.github/workflows/build_xcframework_manual.yml, .github/workflows/cocoapods.yml, .github/workflows/cocoapods_beta.yml, .github/workflows/cocoapods_beta_manual.yml, .github/workflows/draft_release_with_tag.yml, .github/workflows/draft_release_without_tag.yml, .github/workflows/spm.yml, scripts/generate_xcframework.sh
最新 macos-14 runner image 把 visionOS SDK 移除了，本 PR 按照官方修改建议，添加 visionOS SDK 下载步骤
=> build: download visionOS SDK if needed

Example/Podfile.lock, GrowingAnalytics.podspec, GrowingTrackerCore/DeepLink/GrowingAppDelegateAutotracker.m, GrowingTrackerCore/GrowingRealTracker.m, GrowingTrackerCore/GrowingTrackConfiguration.m, GrowingTrackerCore/GrowingWindow.m, GrowingTrackerCore/Public/GrowingTrackConfiguration.h
* feat: ANLSPI-28053 add sceneDelegateClass option
=> feat: ANLSPI-28053 add sceneDelegateClass option
