growingio/growingio-sdk-ios-autotracker

- GrowingAnalytics.podspec
- GrowingAutotrackerCore/Manager/GrowingStatusBarEventManager.h
- GrowingAutotrackerCore/Manager/GrowingStatusBarEventManager.m
- GrowingAutotrackerCore/WebCircle/GrowingStatusBarAutotracker.h
- GrowingAutotrackerCore/WebCircle/GrowingStatusBarAutotracker.m
- GrowingAutotrackerCore/WebCircle/GrowingWebCircle.m
- GrowingTrackerCore/DeepLink/GrowingAppDelegateAutotracker.m
- GrowingTrackerCore/DeepLink/GrowingSceneDelegateAutotracker.m
- GrowingTrackerCore/Event/GrowingVisitEvent.h
- GrowingTrackerCore/Event/GrowingVisitEvent.m
- GrowingTrackerCore/Manager/GrowingSession.m
- GrowingTrackerCore/Menu/GrowingStatusBar.m
iOS 13以上，状态栏点击不再通过touch触发，由UIStatubarManager统一管理，需要hook来监听
> feat: 修复iOS13上状态栏无法点击的bug

- GrowingAutotrackerCore/Autotrack/UICollectionView+GrowingAutotracker.m
- GrowingAutotrackerCore/Autotrack/UITableView+GrowingAutotracker.m
- GrowingTrackerCore/GrowingSwizzle/GrowingSwizzler.h
- GrowingTrackerCore/GrowingSwizzle/GrowingSwizzler.m
方法调用的过程中，如果对象本身有具体实现或通过 resolveInstanceMethod 动态添加了实现，则不会进入 forwardingTargetForSelector 中；
在[此项目](https://github.com/YoloMao/RSSwizzleDemo)中 Proxy.m 查看模拟场景
> fix: realDelegateFromSelector - 避免proxy本身直接或动态实现了该方法

- GrowingTrackerCore/Event/GrowingEventManager.m
vacuum 函数的调用只针对 timingEventDB，是有问题的，将导致 realtimeEventDB 的空闲列表空间永远无法释放。
> fix: 没有释放 realtimeEventDB 数据库的空间

- GrowingTrackerCore/Event/GrowingEventManager.m
- GrowingTrackerCore/FileStorage/GrowingFileStorage.m
- GrowingTrackerCore/GrowingRealTracker.m
- GrowingTrackerCore/Manager/GrowingSession.m
1. 初始化时的版本日志在 logger 中原 level 为 error，改为 info 更加合理
2. debugEnabled 为 YES 时，level = debug
3. debugEnabled 为 NO 时，level  = info
> fix: SDK 初始化时的版本日志 level 改成 info，并兼容 debugEnabled 配置

- GrowingTrackerCore/GrowingRealTracker.m
- GrowingTrackerCore/Thirdparty/GrowingLogger/GrowingLogger.h
- GrowingTrackerCore/Thirdparty/GrowingLogger/GrowingOSLogger.h
- GrowingTrackerCore/Thirdparty/GrowingLogger/GrowingOSLogger.m
- GrowingTrackerCore/Thirdparty/GrowingLogger/GrowingTTYLogger.m
1. iOS 10+：ASLLogger 和 TTYLogger 同时使用会在 Xcode console 重复打印，建议使用 OSLogger 代替
https://github.com/CocoaLumberjack/CocoaLumberjack/issues/765
https://github.com/CocoaLumberjack/CocoaLumberjack/pull/850
2. 在 Debug 环境下，Simulator 调试日志无法在 console.app 查看，可在终端输入以下指令查看：
```Objective-C
xcrun simctl spawn booted log stream\
--process Example\
--level Debug\
--predicate 'senderImagePath CONTAINS "GrowingAnalytics"'
```
> [Console app not showing info and debug logs](https://developer.apple.com/forums/thread/82736?answerId=422465022#422465022)
> [Using os_log and log streaming on iOS](https://www.iosdev.recipes/simulator/os_log/)
3. os_log/NSLog 1024 Bytes 截断问题暂时无法解决，在 console.app 显示日志将被截断，不影响 Xcode console
https://github.com/darlinghq/darling/blob/2e341e8c7c3ac5d0559ecbe2dd7dc64efa110bf4/src/libc/os/log …
> fix: 日志重复打印问题（Xcode console），且在 Release 环境下需不可见（console.app）

- GrowingTrackerCore/Event/GrowingEventManager.m
- GrowingTrackerCore/GrowingTrackConfiguration.m
- GrowingTrackerCore/Manager/GrowingSession.h
- GrowingTrackerCore/Manager/GrowingSession.m
- SessionId 刷新、VISIT 事件发送与安卓 SDK 保持一致
- 显示通知中心/系统权限授权弹窗显示应重新计算 backgroundTime
测试场景：https://github.com/growingio/growingio-sdk-ios-autotracker/pull/138#issue-715845960
> fix: SessionId 刷新、VISIT 事件发送与安卓 SDK 保持一致

- GrowingTrackerCore/GrowingRealTracker.m
- GrowingTrackerCore/Manager/GrowingSession.m
在线程资源紧张的情况下，GrowingEventManager 可能在主线程初始化（一般情况在 Growing Thread 中与事件创建串行），并在 主线程向 Growing Thread 注册数据库和事件队列的创建（`performSelector:OnThread:withObject:waitUntilDone:`），将导致 generateVisitEvent 函数调用时认为 GrowingEventManager 已创建且数据库配置等已完成。
注: 数据库配置等在 Growing Thread 线程执行是为了降低 SDK 初始化耗时。
未修改: 
------------------------------------------------------
线程资源紧张情况：
```Objective-C
+[GrowingEventManager sharedInstance](Main Thread)->
-[GrowingEventManager postEventBuidler:](Growing Thread, eventQueue = nil, send VISIT failure)->
-[GrowingEventManager reloadFromDB_unsafe](Growing Thread, eventQueue = [])
```
正常情况：
```Objective-C
+[GrowingEventManager sharedInstance](Growing Thread)->
-[GrowingEventManager reloadFromDB_unsafe](Growing Thread, eventQueue = [])->
-[GrowingEventManager postEventBuidler:](Growing …
```
> fix: 线程资源紧张的情况下，VISIT 可能丢失

- GrowingTrackerCore/Event/GrowingEventManager.h
- GrowingTrackerCore/Event/GrowingEventManager.m
- GrowingTrackerCore/Manager/GrowingSession.m
- GrowingTrackerCore/Thread/GrowingDispatchManager.h
- GrowingTrackerCore/Thread/GrowingDispatchManager.m
杀死进程时，Growing Thread 优先级较低，导致无法完成 APP_CLOSED 事件的入库，利用线程同步来确保事件 Build 及入库
是否需要使用 beginBackgroundTaskWithExpirationHandler<sup>[1]</sup> 函数确保进程前台切换至后台时，事件正常入库？
答：使用 B***u App 测试，目前使用线程同步确认的方式效果正常，暂不需要使用 beginBackgroundTaskWithExpirationHandler 函数来延长 Background 执行时间
1. debugEnabled 需为 NO，为 YES 则事件会立即入库，影响最终测试结果；
2. 断开数据线连接测试，连接调试的情况下，Watchdog<sup>[2]</sup> 机制无效；
3. 当进程处于 Suspended 状态下，杀死进程将不会收到 UIApplicationWillTerminateNotification<sup>[3]</sup> 通知；
*[1] [beginBackgroundTaskWithExpirationHandler](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtaskwithexpiratio)*
*[2] [Watchdog maximum time is 10 sec for suspend state](https://stackoverflow.com/questions/59827727/ios-frequently-getting-exhausted-real-wall-clock-time-allowance-of-10-00-seco)*
*[3] …
> fix: 杀死进程 APP_CLOSED 未发送

- GrowingAutotracker/GrowingAutotracker.h
- GrowingAutotracker/GrowingAutotracker.m
- GrowingAutotrackerCore/GrowingAutotrackConfiguration.h
- GrowingAutotrackerCore/GrowingAutotrackConfiguration.m
- GrowingAutotrackerCore/GrowingNode/Category/UIView+GrowingNode.m
- GrowingAutotrackerCore/GrowingNode/Category/UIViewController+GrowingNode.h
- GrowingAutotrackerCore/GrowingNode/Category/UIViewController+GrowingNode.m
- GrowingAutotrackerCore/GrowingRealAutotracker.h
- GrowingAutotrackerCore/GrowingRealAutotracker.m
- GrowingAutotrackerCore/Page/UIViewController+GrowingPageHelper.m
- GrowingAutotrackerCore/Private/GrowingPrivateCategory.h
- GrowingTracker/GrowingTracker.h
- GrowingTracker/GrowingTracker.m
- GrowingTrackerCore/GrowingRealTracker.m
- Modules/WebCircle/GrowingWebCircle.m
cdp 在 trackerWithConfiguration:launchOptions: 函数之后才添加的拦截器，用于userId 改变时持久化 gioId 以及发数前添加 gioId；
generateVisit 时机早于拦截器，将使 gioId 未附带上传。
cdp 初始化 SDK 后首次发送的 VISIT 事件附带的 gioId、dataSourceId 是否正常。
> fix: cdp Interceptor 添加 gioId 失效

- GrowingAutotrackerCore/GrowingNode/Category/UIView+GrowingNode.h
- Modules/Hybrid/GrowingHybridModule.m
- Modules/Hybrid/GrowingWKWebViewJavascriptBridge.h
- Modules/Hybrid/GrowingWKWebViewJavascriptBridge.m
- Modules/Hybrid/WKWebView+GrowingAutotracker.h
- Modules/Hybrid/WKWebView+GrowingAutotracker.m
可通过配置`webView.growingViewIgnorePolicy`来控制是否注入 WebView Bridge
1. WebView Bridge 注入延后至`loadRequest`等函数
2. GrowingWKWebViewJavascriptBridge 调整为**单例**
3. 使用`webView.growingViewDontTrack`判断 webView 是否可 track，`webView.growingNodeDonotTrack`中`webView.window`在更新界面之前会返回 nil
```Objective-C
- (void)viewDidLoad {
[super viewDidLoad];
WKWebView *webView = ...
NSURLRequest *request = ...
[self.view addSubview:webView];
[webView loadRequest:request]; // 此时 webView.window = nil
}
```
1. 设置`webView.growingViewIgnorePolicy = GrowingIgnoreSelf` 或 `webView.growingViewIgnorePolicy = GrowingIgnoreAll`，测试 webView 是否发送埋点事件；
2. 设置`webView.growingViewIgnorePolicy = GrowingIgnoreNone` 或 `webView.growingViewIgnorePolicy = GrowingIgnoreChildren`，测试 webView 是否发送埋点事件；
3. 设置 `webView.superview.growingViewIgnorePolicy = …
> fix: WebView Bridge 注入延后至 loadRequest:

- GrowingTrackerCore/GrowingRealTracker.m
插件可通过配置 podspec
```Ruby
s.pod_target_xcconfig = { 'OTHER_LDFLAGS => -Wl,-U,_GrowingTrackerVersionName' }
```
之后，再在具体实现中
```Objective-C
extern NSString *const GrowingTrackerVersionName;
```
来获取值。
但这种方式无法与 ENABLE_BITCODE 兼容
```
ld: -U and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
```
出于插件的集成尽量不改变宿主工程配置考虑，使用另一种方案：SDK 中添加 version 获取相关实现，插件中使用反射或 Objective-C Runtime 来获取。
> feat: 新增 version 相关接口 (Private)，提供给 GrowingToolsKit 调用

- GrowingAnalytics.podspec
- GrowingTrackerCore/GrowingRealTracker.m
- GrowingTrackerCore/GrowingTrackConfiguration.h
- GrowingTrackerCore/GrowingTrackConfiguration.m
- GrowingTrackerCore/NetWork/Request/Adapter/GrowingEventRequestAdapter.m
- Configuration 增加 EncryptEnabled 配置项，默认值为 NO，不开启加密
- 通过日志提示原有的 subspec `ENABLE_ENCRYPTION`已废弃
- 版本号改为`3.3.1-hotfix.1`
- 集成`pod 'GrowingAnalytics/ENABLE_ENCRYPTION'`，并`setEncryptEnabled = YES`，加密为开启状态
- 集成`pod 'GrowingAnalytics/ENABLE_ENCRYPTION'`，并`setEncryptEnabled = NO`，加密为开启状态（旧版本兼容）
- 不集成`pod 'GrowingAnalytics/ENABLE_ENCRYPTION'`，并`setEncryptEnabled = YES`，加密为开启状态
- 不集成`pod 'GrowingAnalytics/ENABLE_ENCRYPTION'`，并`setEncryptEnabled = NO`，加密为关闭状态
- 集成文档需要更新 EncryptEnabled 配置项，并去除`pod 'GrowingAnalytics/ENABLE_ENCRYPTION'`的方式
- 兼容 SDK 旧版本
无
> feat: Configuration 增加 EncryptEnabled 配置项

- GrowingAnalytics.podspec
- GrowingTrackerCore/Core/GrowingAnnotationCore.m
- GrowingTrackerCore/Core/GrowingModuleManager.h
- GrowingTrackerCore/Core/GrowingModuleManager.m
- GrowingTrackerCore/Core/GrowingServiceManager.h
- GrowingTrackerCore/Core/GrowingServiceManager.m
- GrowingTrackerCore/GrowingRealTracker.m
修改dyld回调中，只存入string字符串，减少dyld回调期间操作，将moduleInfo生成放入sdk初始化中
模块以及service功能响应应正常，不受影响
无
Close #168 , 并不是修复 #168 的问题，只是与其相关
> fix: dyld不调用NSClassFromString

- GrowingAnalytics.podspec
- GrowingTrackerCore/Core/GrowingAnnotationCore.h
- GrowingTrackerCore/Core/GrowingAnnotationCore.m
- GrowingTrackerCore/Core/GrowingModuleManager.h
- GrowingTrackerCore/Core/GrowingModuleManager.m
- GrowingTrackerCore/Core/GrowingServiceManager.h
- GrowingTrackerCore/Core/GrowingServiceManager.m
- GrowingTrackerCore/Core/Services/GrowingEventDatabaseService.h
- GrowingTrackerCore/DataBase/GrowingEventDatabase.m
- GrowingTrackerCore/GrowingRealTracker.m
- Modules/Hybrid/GrowingHybridModule.m
- Modules/MobileDebugger/GrowingMobileDebugger.m
- Modules/WebCircle/GrowingWebCircle.m
- Services/Compression/GrowingDataCompression.m
- Services/Database/GrowingEventFMDatabase.m
- Services/Encryption/GrowingDataEncoder.m
- Services/Network/GrowingNetworkManager.m
- Services/WebSocket/GrowingSRWebSocket.m
对 dyld callback中的操作，使用纯c处理，防止与百度sdk冲突，该冲突问题是：百度sdk在异步持有runtime lock时，又请求dyld lock，而我们sdk，主线程中持有dyld lock时，由于使用 NSString 等oc类，会请求runtime lock，导致死锁。
pod 'BaiduMapKit','6.3.1' 与百度sdk兼容测试通过，问题为偶现
影响 module 和 service 的加载
无
> fix: 对dyld部分操作使用纯c实现，避开runtime冲突

- Example/Example/UICategoryTests/GIOButtonViewController.m
- Example/Example/UICategoryTests/GIOLabelAttributeViewController.m
- 替换 Demo 中的 UIAlertView API 调用，改为 UIAlertController（UIAlertView 于 iOS 8 废弃）
* 测试 UI界面->Button&AlertView，各个按钮触发的弹窗是否正常
* 测试 UI界面->AttributeLabel，ShowAlert 按钮触发的弹窗是否正常
无
https://developer.apple.com/documentation/uikit/uialertview
https://developer.apple.com/documentation/uikit/uialertcontroller
> fix: 替换 Demo 中的 UIAlertView API 调用，改用 UIAlertController

- GrowingAutotrackerCore/GrowingNode/Category/UIViewController+GrowingNode.h
- GrowingAutotrackerCore/GrowingNode/Category/UIViewController+GrowingNode.m
- GrowingTrackerCore/DeepLink/GrowingAppDelegateAutotracker.m
- GrowingTrackerCore/Helpers/NSDictionary+GrowingHelper.h
- GrowingTrackerCore/Helpers/NSDictionary+GrowingHelper.m
- fix: 设置 growingPageAttributes 页面变量为 nil 时，导致崩溃
- fix: GrowingAppDelegateAutotracker.m 合并冗余代码
设置 growingPageAttributes 为 nil
- growingPageAttributes 设置为普通 NSDictionary 对象，是否正常
- growingPageAttributes 设置为 Large NSDictionary 对象，是否正常
- growingPageAttributes 设置为 nil，是否正常
无
> fix: setGrowingPageAttributes nil crash

- Example/Example/UICategoryTests/Hybrid/gio_hybrideventtest.html
- GrowingTrackerCore/Event/GrowingEventManager.m
- Modules/WebCircle/GrowingWebCircle.m
- Crash:
```
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <NSConcreteHashTable: 0x2839ebf20> was mutated while being enumerated.'
*** First throw call stack:
(0x182b7c05c 0x19b096f54 0x182c520e8 0x184328764 0x104a5f3d4 0x104a52ba8 0x104a52ad4 0x104a5f228 0x104a5da18 0x104a52c78 0x18434ae0c 0x182b9e030 0x182baecf0 0x182ae8ff8 0x182aee804 0x182b023c8 0x184325d54 0x104aa18e4 0x18437595c 0x1f2fb1a60 0x1f2fb0f5c)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** …
```
> fix: 边界情况下，点击退出圈选同时产生事件，可能导致 Crash

- Example/Example/MeasurementProtocol/CustomEvent/GIOCustomEventViewController.m
- Example/GrowingAnalyticsTests/A0GrowingAnalyticsCDPTest.m
- Example/GrowingAnalyticsTests/A0GrowingAnalyticsTest.m
- GrowingAnalytics-cdp/GrowingAutotracker/GrowingAutotracker.h
- GrowingAnalytics-cdp/GrowingTracker/GrowingTracker.h
- GrowingAnalytics.xcworkspace/xcshareddata/IDETemplateMacros.plist
- GrowingAnalytics/GrowingAutotracker/GrowingAutotracker.h
- GrowingAnalytics/GrowingTracker/GrowingTracker.h
- GrowingAnalytics/GrowingTrackerCore/Event/Base/GrowingAttributesBuilder.h
- GrowingAnalytics/GrowingTrackerCore/Event/Base/GrowingAttributesBuilder.m
- GrowingAnalytics/GrowingTrackerCore/GrowingRealTracker.h
- GrowingAnalytics/GrowingTrackerCore/GrowingRealTracker.m
- Podfile.lock
- README.md
事件属性支持 list
示例代码如下：
```Objective-C
GrowingAttributesBuilder *builder = GrowingAttributesBuilder.new;
[builder setString:@"value" forKey:@"key"];
[builder setArray:@[@"value1", @"value2", @"value3"] forKey:@"key2"];
[GrowingAutotracker.sharedInstance trackCustomEvent:@"eventName" withAttributesBuilder:builder];
```
- 如示例代码，测试 CUSTOM 事件属性添加 Array 上报是否正常
- 测试边界情况（类型不符等，见单测）下，该接口调用是否有所提示，且不报错
- 单元测试通过
- CUSTOM 事件属性上报
无
> feat: 事件属性支持 list

- Example/GrowingAnalyticsTests/A0GrowingAnalyticsCDPTest.m
- Example/GrowingAnalyticsTests/A0GrowingAnalyticsTest.m
- GrowingAnalytics/GrowingTrackerCore/Event/Base/GrowingAttributesBuilder.h
- GrowingAnalytics/GrowingTrackerCore/Event/Base/GrowingAttributesBuilder.m
- CUSTOM 事件属性支持 NSArray<ObjectType>，优化参数判断，补充单元测试
**其中 Key 必须是 NSString 类型，且不能为空字符串**
示例代码如下：
```Objective-C
GrowingAttributesBuilder *builder = GrowingAttributesBuilder.new;
[builder setString:@"value" forKey:@"key"];
[builder setArray:@[@"value1", @"value2", @"value3"] forKey:@"key2"];
[builder setArray:@[@1, @2, @3] forKey:@"key3"];
[builder setArray:@[@[@"1"], @[@"2"], @[@"3"]] forKey:@"key4"];
[builder setArray:@[@{@"value":@"key"}, @{@"value":@"key"}, @{@"value":@"key"}] forKey:@"key5"];
[builder setArray:@[NSObject.new, NSObject.new, NSObject.new] forKey:@"key6"];
[[GrowingAutotracker sharedInstance] trackCustomEvent:@"eventName"
withAttributesBuilder:builder];
```
- **补充** https://github.com/growingio/growingio-sdk-ios-autotracker/pull/195
- 如示例代码，测试 CUSTOM 事件属性添加 Array 上报是否正常
- …
> feat: CUSTOM 事件属性支持 NSArray<ObjectType>，优化参数判断，补充单元测试

- GrowingTrackerCore/Event/GrowingEventManager.h
- GrowingTrackerCore/Event/GrowingEventManager.m
- GrowingTrackerCore/GrowingRealTracker.m
- fix: GrowingEventManager 在 loadLocalServices 之前初始化将导致数据库创建失败，事件无法入库
SDK 3.3.2 版本及以上，同时集成 [GrowingAnalytics-upgrade](https://github.com/growingio/growingio-sdk-ios-autotracker-upgrade) 以迁移 SDK 2to3 时，会导致埋点事件以及部分无埋点事件丢失
- 原因：
https://github.com/growingio/growingio-sdk-ios-autotracker/pull/172 将**所有预置 Services 注册(包括 Database Service)** 延后至 SDK 初始化时，而 GrowingAnalytics-upgrade 在 **+load 时期**调用了`+[GrowingEventManager sharedInstance]`提前初始化数据库，导致数据库因未配置 Services Class 创建失败
- 修改方案：
将`+[GrowingEventManager sharedInstance]`中**初始化数据库、初始化流量控制变量**等逻辑迁移到`-[GrowingEventManager configManager]`，保证`+[GrowingEventManager sharedInstance]`的调用不会对事件存储与发送造成影响
- Podfile 集成：
```ruby
pod 'GrowingAnalytics-upgrade/Autotracker-upgrade-2to3-cdp'
pod 'GrowingAnalytics-cdp/Autotracker'
```
- 执行 pod install
- 通过抓包工具或 …
> fix: GrowingEventManager 在 loadLocalServices 之前初始化将导致数据库创建失败，事件无法入库

- Example/Example.xcodeproj/project.pbxproj
- Example/Example/AppDelegate.m
- Example/Example/MeasurementProtocol/AttributesEvent/GIOAttributesTrackViewController.m
- Example/Example/MeasurementProtocol/CustomEvent/GIOCustomEventViewController.m
- Example/GrowingAnalyticsTests/A0GrowingAnalyticsCDPTest.m
- Example/GrowingAnalyticsTests/A0GrowingAnalyticsTest.m
- GrowingAutotracker-cdp/GrowingAutotracker.h
- GrowingAutotracker/GrowingAutotracker.h
- GrowingTracker-cdp/GrowingTracker.h
- GrowingTracker/GrowingTracker.h
- GrowingTrackerCore/Event/Base/GrowingAttributesBuilder.m
- GrowingTrackerCore/GrowingRealTracker.h
- GrowingTrackerCore/GrowingRealTracker.m
- Podfile
- Podfile.lock
- feat: LOGIN_USER_ATTRIBUTES 事件属性支持 NSArray<ObjectType\>
**其中 Key 必须是 NSString 类型，可为空字符串**
**当事件属性为 `NSArray<NSNull *>` 类型时，NSNull 转为空字符串**
示例代码如下：
```Objective-C
GrowingAttributesBuilder *builder = GrowingAttributesBuilder.new;
[builder setString:@"value" forKey:@"key"];
[builder setArray:@[@"value1", @"value2", @"value3"] forKey:@"key2"];
[builder setArray:@[@1, @2, @3] forKey:@"key3"];
[builder setArray:@[@[@"1"], @[@"2"], @[@"3"]] forKey:@"key4"];
[builder setArray:@[@{@"value":@"key"}, @{@"value":@"key"}, @{@"value":@"key"}] forKey:@"key5"];
[builder setArray:@[NSObject.new, NSObject.new, NSObject.new] forKey:@"key6"];
[builder setArray:@[NSNull.new, NSNull.new, NSNull.new] forKey:@"key7"];
[builder setArray:@[@"value1", @"value2", @"value3"] forKey:@""];
[[GrowingAutotracker …
```
> feat: LOGIN_USER_ATTRIBUTES 事件属性支持 NSArray<ObjectType>

- GrowingTrackerCore/Event/GrowingEventManager.h
- GrowingTrackerCore/Event/GrowingEventManager.m
- feat: GrowingEventInterceptor 增加 EventDidWrite 回调，以便新增事件排序
- CI 通过
拦截器新增事件的先后入库、发送顺序
如果在 EventDidBuild 进行拦截新增事件，被拦截的事件尚未入库，将导致新增的事件入库早于被拦截的事件，虽然 globalSequenceId / eventSequenceId 的顺序正确，但发送时新增的事件也会早于被拦截的事件。
> feat: GrowingEventInterceptor 增加 EventDidWrite 回调，以便新增事件排序

- Example/GrowingAnalyticsTests/AutotrackerCoreTests/Autotrack/UICollectionViewAutotrackTest.m
- Example/GrowingAnalyticsTests/AutotrackerCoreTests/Autotrack/UITableViewAutotrackTest.m
- GrowingTrackerCore/Swizzle/GrowingSwizzler.m
- fix: 避免因 delegate 对象重写 class 方法导致 swizzle 失效
- test: 补充单元测试 - UITableView / UICollectionView setDelegate 对象重写 class 方法
- CI 通过
- UITableView / UICollectionView 无埋点点击事件
- 与火山引擎的 UITableView / UICollectionView setDelegate Hook 起冲突
> fix: 避免因 delegate 对象重写 class 方法导致 swizzle 失效

- GrowingAnalytics-cdp.podspec
- GrowingAnalytics.podspec
- GrowingTrackerCore/GrowingRealTracker.m
- Services/Database/FMDB/GrowingFMDatabase.h
- Services/Database/FMDB/GrowingFMDatabase.m
- Services/Database/FMDB/GrowingFMDatabaseAdditions.m
- Services/Database/FMDB/GrowingFMDatabasePool.h
- Services/Database/FMDB/GrowingFMDatabaseQueue.h
- Services/Database/FMDB/GrowingFMResultSet.h
- Services/Database/FMDB/GrowingFMResultSet.m
- fix: 系统库文件如 sqlite3.h 应使用尖括号导入，而不是引号
- CI 通过
- 同时集成 SQLCipher，能够正常编译运行，`pod 'SQLCipher'`
- 同时集成其他第三方库 (比如 SQLCipher) 且其内部重写了 sqlite3.h 作为 Public Header 时，应该正常编译运行
- https://stackoverflow.com/questions/50361079/sqlite3-h-file-not-found-after-pod-firebasemessaging-update
> fix: 系统库文件如 sqlite3.h 应使用尖括号导入，而不是引号

- Modules/WebCircle/GrowingWebCircle.m
- fix: parentView 不可见时，圈选遍历上报的 elements 不应该包含其 subViews
圈选时，如果不可见的控件也包含在内，则会导致 z-Index 较低的可圈选控件被遮挡而无法圈选
1. 在 Demo 中任意 ViewController viewDidLoad 方法中添加如下代码：
```Objective-C
UIView *view = [[UIView alloc] initWithFrame:self.view.bounds];
UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
button.frame = view.bounds;
[button addTarget:self action:@selector(description) forControlEvents:UIControlEventTouchUpInside];
[view addSubview:button];
[self.view addSubview:view];
// parentView 不可见，则圈选上报 elements 不应该包含 parentView 内部的 subViews
view.hidden = YES;
```
2. 进行圈选验证是否正常
- 无埋点圈选
无
> fix: HZSSI-2001 parentView 不可见时，圈选遍历不应该包含 subViews

- GrowingAutotrackerCore/Page/GrowingPageManager.m
- fix: 修复延迟初始化下 PAGE 漏发、page.path 不准确
#232 
- fix: 修复延迟初始化下 VIEW_CLICK、VIEW_CHANGE 事件参数异常，圈选显示截图异常
#234 
在 AppDelegate 以下代码中初始化 SDK 进行测试 PAGE 事件的发送：
```objc
- (void)applicationDidBecomeActive:(UIApplication *)application {
NSLog(@"Application - applicationDidBecomeActive");
if (@available(iOS 14, *)) {
[ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {
dispatch_async(dispatch_get_main_queue(), ^{
// 初始化SDK
// ...
});
}];
} else {
// 初始化SDK
// ...
}
}
```
- PAGE 事件正常发送
- PAGE 事件中 path 字段值
- 未创建 GrowingPage 对象的页面 VIEW_CLICK / VIEW_CHANGE 事件中 path、pageShowTimestamp 字段值
- 圈选截图展示正常
- 在平台上使用错误 path 定义的页面需要重新定义
无
> fix: 修复延迟初始化下 PAGE 漏发、page.path 不准确等一系列问题

- Example/Example/AppDelegate.m
- GrowingTrackerCore/Manager/GrowingSession.h
- GrowingTrackerCore/Manager/GrowingSession.m
- Modules/Advert/GrowingAdvertising.m
- Podfile.lock
如当前 App 位于前台，则直接发送唤醒事件；
如当前 App 处于后台，当回到前台后，先发送 VISIT 事件，再发送唤醒事件
见：https://jira.startdt.net/browse/ANLSPI-3341
- CI 通过
- Advert Module
无
> fix: app 切后台超过 30s，其唤醒事件 SessionId 未刷新

- CHANGELOG.md
- Example/Example.xcodeproj/project.pbxproj
- Example/Example/AppDelegate.m
- GrowingAnalytics-cdp.podspec
- GrowingAnalytics.podspec
- GrowingAutotrackerCore/Impression/GrowingImpressionTrack.m
- GrowingAutotrackerCore/Page/GrowingPageManager.m
- GrowingTrackerCore/Event/GrowingEventManager.m
- GrowingTrackerCore/GrowingRealTracker.m
- GrowingTrackerCore/Public/GrowingFlutterService.h
- Modules/Flutter/GrowingFlutterPlugin.h
- Modules/Flutter/GrowingFlutterPlugin.m
- Modules/Flutter/GrowingFlutterWebCircleBridge.h
- Modules/Flutter/GrowingFlutterWebCircleBridge.m
- Modules/Flutter/Public/Dummy-GrowingModule-FlutterPlugin.h
- Modules/WebCircle/GrowingWebCircle.m
- Podfile
- Podfile.lock
- README.md
- codecov.yml
- sonar-project.properties
~~A. 适配flutter无埋点功能，添加flutterplugin类，用于原生和flutter之间相互传值，同时flutter的无埋点插件[flutter-growingio-sdk-autotracker-plugin](https://github.com/growingio/flutter-growingio-sdk-autotracker-plugin)会依赖这里的flutter模块，使得默认情况下无flutter埋点相关代码，但如果集成了flutter的无埋点插件[flutter-growingio-sdk-autotracker-plugin](https://github.com/growingio/flutter-growingio-sdk-autotracker-plugin)，则会加入flutter相关的代码功能~~
~~B. fix了圈选部分，在不杀死app情况下，再次圈选时无响应的问题bug~~
~~1. 正常sdk使用圈选时，无flutter模块，且功能正常~~
~~2. 使用 [flutter-growingio-sdk-autotracker-plugin](https://github.com/growingio/flutter-growingio-sdk-autotracker-plugin) 时，会自动导入flutter模块~~
~~3. 两种情况下圈选功能都应正常~~
~~4. 圈选退出后，不杀死app，再扫码圈选，此时应该能够继续圈选~~
~~仅有概率会影响圈选逻辑~~
无
> feat: 适配flutter无埋点

- Services/WebSocket/GrowingSRWebSocket.m
* fix: Remove usage of deprecated Endian with CFSwap
https://github.com/facebookincubator/SocketRocket/commit/b666a4559ab8295e84f962899b4e3ece4288a7c2
* CI 通过
* WebSocket 中字节大小端转换
* 使用到 WebSocket 的 MobileDebugger、WebCircle 模块
无
> fix: Remove usage of deprecated Endian with CFSwap

- GrowingTrackerCore/Thirdparty/Logger/GrowingLog.m
[dispatch_semaphore_wait](https://developer.apple.com/documentation/dispatch/1453087-dispatch_semaphore_wait) 在使用过程中容易造成优先级反转问题
> If you use concurrency primitives, such as [dispatch_semaphore_wait](https://developer.apple.com/documentation/dispatch/1453087-dispatch_semaphore_wait) and [dispatch_group_wait](https://developer.apple.com/documentation/dispatch/1452794-dispatch_group_wait), in your code or invoke APIs that use them, your app is susceptible to priority inversions if there is a mismatch in the quality-of-service (QoS) class of the dispatch queues your app uses. When you use these primitives, the system can’t automatically propagate priority from the higher-priority thread to the lower-priority thread.
在原实现中，在同一时刻，GrowingLOG_MAX_QUEUE_SIZE + 1 次调用 dispatch_semaphore_wait …
> fix: priority inversion issue by Xcode14 thread performance checker

- GrowingTrackerCore/FileStorage/GrowingFileStorage.m
- GrowingTrackerCore/Helpers/Foundation/NSData+GrowingHelper.m
- Modules/Advert/AppleSearchAds/GrowingAsaFetcher.m
* fix: 修复特殊场景下，每当初始化 SDK，ASAFetcher 都会 startFetch (Advert)
1. 注释 setActivateSent 内部代码，模拟特殊场景 (如本地缓存文件写入失败) https://github.com/growingio/growingio-sdk-ios-autotracker/blob/7342a8eeba888760e77f4a0281978d7bb31f3b4d/Modules/Advert/Utils/GrowingAdUtils.m#L186
2. 首次运行启动 App，等待发送激活事件 (此时由于步骤 1，setActivateSent 内代码未执行，所以已发送激活事件的本地标记缓存未存储)
3. 发送成功后，反注释步骤 1 的代码，杀掉 App 再次运行，还是会开启 ASAFetcher 并请求 ASA 数据，此为异常
正常情况下，激活事件已发送，则 ASAFetcher 不再去请求获取，GrowingAsaFetcher.status 直接为 GrowingAsaFetcherStatusCompleted
- Advert Module
无
> fix: 修复特殊场景下，每当初始化 SDK，ASAFetcher 都会 startFetch (Advert)

- Example/Example/UICategoryTests/H5Browser/GIODefaultWebViewController.m
- Example/Example/UICategoryTests/Hybrid/GIOHybridViewController.m
使用 Xcode 14.3 链接 iOS SDK 16.4 编译时，需要设置 `webView.inspectable = YES; `，否则无法通过 Safari 调试
> test: enable inspection of webView in iOS 16.4

- Example/Example/AppDelegate.m
- Example/Example/Example.entitlements
- Example/ExampleiOS13/ExampleiOS13.entitlements
- Modules/Advert/GrowingAdvertising.m
- Modules/Advert/Public/GrowingAdvertising.h
- Modules/Advert/Request/GrowingAdPreRequest.m
- Modules/Advert/Utils/GrowingAdUtils.m
* fix: default deep link host
* fix: verify deep link host
* 使用非法 deepLinkHost (如，包含空格、IP) 进行初始化，是否报错
* 初始化若未配置 deepLinkHost，将使用默认地址
> fix: verify deep link host

- GrowingAutotracker-cdp/GrowingAutotracker.h
- GrowingTracker-cdp/GrowingTracker.h
* fix: swift project building error about 'Include of non-modular header inside framework module'
* 新建 **Swift** 项目，使用 **Cocoapods** 集成 **GrowingAnalytics-cdp SDK** 进行测试
* SDK 在 Swift 项目下使用 Cocoapods 集成后可正常编译
* 参考：*https://clang.llvm.org/docs/LanguageExtensions.html#modules*
* 如果 https://github.com/growingio/growingio-sdk-ios-autotracker/pull/250 合并，则此 PR 可作废
* 集成文档中，对应描述 - [Include of non-modular header inside framework module 报错解决方案](https://growingio.github.io/growingio-sdk-docs/docs/ios/Introduce#include-of-non-modular-header-inside-framework-module-%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)，可在此 PR 合并后，删除或改成当所使用的 SDK 为对应 SDK 版本(3.3.5-<此 PR 合并前的版本>)情况下
> fix: swift project building error

- Example/Example.xcodeproj/project.pbxproj
- GrowingAnalytics.podspec
- Modules/V2Adapter/GrowingAutoTrackKit.m
- Modules/V2Adapter/Public/GrowingAutoTrackKit.h
- Modules/V2AdapterTrackOnly/GrowingCoreKit.m
- Modules/V2AdapterTrackOnly/GrowingV2Adapter.m
- Modules/V2AdapterTrackOnly/Public/Growing.h
- Modules/V2AdapterTrackOnly/Public/GrowingCoreKit.h
- Modules/V2AdapterTrackOnly/Public/GrowingV2Adapter.h
- Podfile
- Podfile.lock
> feat: v2 to v3+ adapter

- Services/SwiftProtobuf/SwiftProtobuf.swift
* fix: swift protobuf 中 timezoneOffset 数据类型为 String
* fix: swift protobuf 中 toJson 后 timestamp 应为 Number 类型
见：https://github.com/growingio/growingio-sdk-ios-autotracker/pull/248#issuecomment-1515913736
> Int64 类型在 proto3 JSON Mapping 默认为 String 类型，apple/swift-protobuf 提供将 Int64 转为 Number，但截止 1.21.0 版本，尚未合并到发布分支上；对于 SDK运行过程中，~~toJSON 仅在打印调试日志 / Advert 模块获取 eventName 时调用，Int64 转 String 或 Number 并不影响功能正常执行；~~
现在 SDK 有 3.x 升到 4.x 的逻辑，如果在 3.x 集成了 SwiftProtobuf 模块产生了事件并且没发送，升级到 4.x 后又通过初始化配置 `config?.useProtobuf = false` 使用 JSON 类型发送该事件，那么经由 apple/swift-protobuf 转化过后的事件字段 `timestamp`（目前 SDK 中仅 timestamp 为 Int64）为 String 是不正确的，应该改成 Number
> fix: some bugs in swift protobuf

- .github/workflows/spm.yml
之前 xcodebuild 产生的日志通过 xcpretty 打印，导致 xcodebuild 就算出错，也会产出日志，转到 xcpretty。这种场景下，整个 job 也算执行成功。因此，https://github.com/growingio/growingio-sdk-ios-autotracker/commit/ed7751bcc78db497fbfdf1d8dc744890dff0b446 改动前，没有判定出异常
> ci: spm.yml 中 xcodebuild 未主动报错

- .github/workflows/spm.yml
- Package.swift
SDK 4.0.0 开始，由于接口改动的原因，utils/performance 都以 version 1.0.0 来依赖，与 SDK 3.x 区分开
> fix: update spm dependency version

- Example/Example.xcodeproj/project.pbxproj
- Example/Example/AppDelegate.m
- Example/ExampleiOS13/AppDelegate.m
- Example/GrowingAnalyticsTests/A0GrowingAnalyticsTest.m
- Example/GrowingAnalyticsTests/AutotrackerCoreTests/Autotrack/NSNotificationCenterAutotrackTest.m
- Example/GrowingAnalyticsTests/AutotrackerCoreTests/Autotrack/UICollectionViewAutotrackTest.m
- Example/GrowingAnalyticsTests/AutotrackerCoreTests/Autotrack/UITableViewAutotrackTest.m
- Example/GrowingAnalyticsTests/GrowingAnalyticsStartTests/GrowingAnalyticsStartTests.m
- Example/GrowingAnalyticsTests/GrowingAnalyticsStartTests/GrowingAnalyticsStartTests2.m
- Example/GrowingAnalyticsTests/ModulesTests/AdvertTests/AdvertTest.m
- Example/GrowingAnalyticsTests/ModulesTests/HybridTests/HybridTest.m
- Example/GrowingAnalyticsTests/ModulesTests/ProtobufTests/ProtobufRequestHeaderTest.m
- Example/GrowingAnalyticsTests/TrackerCoreTests/EventTests/EventTest.m
- Example/GrowingAnalyticsTests/TrackerCoreTests/ManagerTests/GrowingSessionTest.m
- GrowingAutotracker/GrowingAutotracker.m
- GrowingAutotrackerCore/GrowingAutotrackConfiguration.m
- GrowingTracker/GrowingTracker.m
- GrowingTrackerCore/Event/GrowingEventManager.m
- GrowingTrackerCore/GrowingTrackConfiguration.m
- GrowingTrackerCore/Network/Request/GrowingEventRequest.m
- GrowingTrackerCore/Network/Request/GrowingNetworkConfig.m
- GrowingTrackerCore/Public/GrowingTrackConfiguration.h
- Modules/Advert/Request/GrowingAdPreRequest.m
- Modules/Hybrid/GrowingWKWebViewJavascriptBridge.m
- Modules/Hybrid/GrowingWebViewJavascriptBridgeConfiguration.h
- Modules/Hybrid/GrowingWebViewJavascriptBridgeConfiguration.m
- Modules/MobileDebugger/GrowingMobileDebugger.m
- Modules/WebCircle/GrowingWebCircle.m
* 将 SDK 中 projectId 重命名为 accountId，与平台一致
* 兼容 Flutter SDK 等其他库，保留 `configurationWithProjectId `调用方式
* MobileDebugger 和 WebCircle 中，**ready** 消息内容还是以 `projectId` 作为 key
* `GrowingWebViewJavascriptBridge.configuration` 还是以 `projectId` 作为 key
> fix: rename projectId to accountId

- GrowingAutotrackerCore/GrowingAutotrackConfiguration.m
- GrowingAutotrackerCore/Page/GrowingPageManager.m
- GrowingAutotrackerCore/Public/GrowingAutotrackConfiguration.h
- Modules/ImpressionTrack/GrowingImpressionTrack.m
* fix(imp): disable impressionTrack module when autotrackEnabled is false
* feat: autotrack-page white list
---
* fix(imp): 当 autotrackEnabled 配置为 false 时，禁用 impressionTrack 模块
* feat: 增加 autotrackPage 白名单配置，其中：
* 当 autotrackAllPages 配置为 true 时，默认所有 viewController 都会追踪，别名为对应的 className
* 配置 autotrackPagesWhiteList (key 为 viewController 对应的 className，value 配置别名)，key 对应的 viewController 会追踪
* 通过 autotrackAllPages、autotrackPagesWhiteList 进行初始化配置验证
* 测试在 autotrackEnabled = false 时，impressionTrack 模块是否还能正常运行
优先级：autotrackPage:alias:attributes: 接口 > autotrackAllPages > autotrackPagesWhiteList
> feat(autotrack): autotrack-page white list

- GrowingAutotrackerCore/Page/GrowingPageManager.m
适配 GioKit 2.0.1 的改动，以正常忽略 GioKit 的页面
https://github.com/growingio/growingio-sdk-ios-toolskit/commit/c6f3d003b59cacfd5406be48d67feb1dff96a27e
通过 autotrackAllPages、autotrackPagesWhiteList 进行初始化配置验证
#301
> fix(autotrack): autotrackAllPages logic

- Example/GrowingAnalyticsTests/GrowingAnalyticsStartTests/GrowingAnalyticsStartTests.m
- Example/GrowingAnalyticsTests/GrowingAnalyticsStartTests/GrowingAnalyticsStartTests2.m
- Example/GrowingAnalyticsTests/ModulesTests/ProtobufTests/ProtobufDatabaseTest.m
- Example/GrowingAnalyticsTests/ServicesTests/DatabaseTests/JSONDatabaseTest.m
- Example/GrowingAnalyticsTests/TrackerCoreTests/DatabaseTests/DatabaseTest.m
- Example/Podfile.lock
- GrowingTrackerCore/Database/GrowingEventDatabase.h
- GrowingTrackerCore/Database/GrowingEventDatabase.m
- GrowingTrackerCore/Event/GrowingEventManager.m
- GrowingTrackerCore/GrowingTrackConfiguration.m
- GrowingTrackerCore/Public/GrowingEventDatabaseService.h
- GrowingTrackerCore/Public/GrowingTrackConfiguration.h
- Modules/DefaultServices/GrowingEventRequestCompressionAdapter.m
- Modules/DefaultServices/GrowingEventRequestEncryptionAdapter.m
- Services/Database/GrowingEventFMDatabase.m
* 添加从数据库获取事件的 data 总长度限制：2MB
* 修复在打开 ASAEnabled 时，因 ACTIVATE 事件延迟发送，从而 events.count 可能为 0，对应的 URLRequest 生成为 nil，导致崩溃产生
* 修复其他可能导致崩溃的场景
* vacuum 操作改为 3 天/次
* 将 encryptEnabled 配置分为 compressEnabled (默认 false) 和 encryptEnabled (默认 false)
* 在 release 环境下，将不再由于 debugEnabled 为 true 而频繁发送事件
> fix: add limit of events data length when query from db

- GrowingTrackerCore/Event/GrowingEventManager.m
使用 instrument 测试发现，打印日志所需调用的 `growingHelper_beautifulJsonString` 函数在 Release 环境下也会调用，导致占用 SDK 线程 15%+ (取决于当前同一时间触发的埋点数，埋点数越多，占用越高) 的 cpu 时间
此 PR 使得在 Release 环境下，不再意外调用 `growingHelper_beautifulJsonString` 函数
> fix(perf): func growingHelper_beautifulJsonString waste a lot of cpu time

- .github/workflows/ci.yml
- Example/Example.xcodeproj/project.pbxproj
- Example/ShareExtension/ShareViewController.m
- GrowingAutotrackerCore/Autotrack/UICollectionView+GrowingAutotracker.m
- GrowingAutotrackerCore/Autotrack/UITableView+GrowingAutotracker.m
- GrowingTrackerCore/DeepLink/GrowingSceneDelegateAutotracker.m
- GrowingTrackerCore/Helpers/UIKit/UIApplication+GrowingHelper.m
- GrowingTrackerCore/Network/GrowingNetworkInterfaceManager.m
- GrowingTrackerCore/Thirdparty/Logger/GrowingLog.h
- GrowingTrackerCore/Utils/GrowingArgumentChecker.h
- GrowingTrackerCore/Utils/GrowingKeyChainWrapper.m
* 修复 UICollectionView/UITableView 的点击无埋点在特殊场景下失效：比如，在 didSelect 方法中同时调用了 reloadData
* 修复部分编译时警告
* 升级 KeyChain 访问相关的代码，主要影响 DeviceId 持久化
> fix: UICollectionView/UITableView swizzle bug

- Example/Example-tvOS/Base.lproj/Main.storyboard
- Example/Example-tvOS/ViewController.swift
- Example/Example.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Podfile.lock
- GrowingAnalytics.podspec
- GrowingAutotrackerCore/Autotrack/UIAlertController+GrowingAutotracker.h
- GrowingAutotrackerCore/Autotrack/UIAlertController+GrowingAutotracker.m
- GrowingTrackerCore/Network/GrowingNetworkInterfaceManager.m
- GrowingTrackerCore/Network/GrowingNetworkPathMonitor.m
- GrowingTrackerCore/Utils/GrowingArgumentChecker.m
- GrowingTrackerCore/Utils/GrowingKeyChainWrapper.m
- Modules/ImpressionTrack/Public/UIView+GrowingImpression.h
- Modules/ImpressionTrack/UIView+GrowingImpressionInternal.m
* imp 模块中，attributes 的类型也从 `[String: String]` 改为 `[String: Any]`
* 修复使用非字符串键设置动态通用属性时崩溃，如下：
```objc
[GrowingAutotracker setDynamicGeneralPropsGenerator:^NSDictionary<NSString *,id> * _Nonnull{
return @{@1:@"1"};
}];
```
* 删除不必要的条件代码，这是由于 `@available(xxx, xxx, *)` 中 `*` 就代表其他平台，且 `API_AVAILABLE` 等价于 `@available(xxx, xxx, *)`。无需再使用宏判断 visionOS 平台
* ANLSPI-18506 修复在 iPad 上弹出的 actionSheet，通过点击变暗的背景视图 dismiss 会崩溃；同时，修复在 iOS 上该操作触发了 3 个 `VIEW_CLICK` 事件，现改为 2 个 (1 个为内部手势触发，1 个为 Cancel Action 触发)
* Google/Protobuf 3.27.0 已于近日发版，添加了 visionOS 平台 Cocoapods 集成支持，本 SDK 也跟进该平台的 Cocoapods 集成支持
> fix: change imp attributes type to [String: Any]

- .github/workflows/ci.yml
- Example/GrowingAnalyticsTests/ModulesTests/ABTestingTests/ABTestingTests.m
- Example/Podfile.lock
- Modules/ABTesting/GrowingABTExperiment+Private.h
- Modules/ABTesting/GrowingABTExperiment.m
- Modules/ABTesting/GrowingABTExperimentStorage.m
- Modules/ABTesting/GrowingABTesting.m
- Modules/ABTesting/Public/GrowingABTExperiment.h
实验入组事件新增预置属性
> [!NOTE]
> 原生端有本地缓存逻辑，需额外注意
> feat(ABTesting): add more parameters to experiment

- Example/Podfile.lock
- GrowingAnalytics-cdp.podspec
- GrowingAnalytics.podspec
- GrowingTrackerCore/GrowingRealTracker.m
- Modules/Protobuf/Catagory/GrowingBaseEvent+Protobuf.m
**Objective-C 项目**，如果没有使用 `use_frameworks! :linkage => :static/dynamic、use_modular_headers!` 等配置进行模块化 pod，则会报错 **Module 'GrowingAnalytics' not found**
前情提要
* #290
> fix: add DEFINES_MODULE to pod_target_xcconfig in order to avoid compile error when without module map

- .github/workflows/draft_release_with_tag.yml
- .github/workflows/draft_release_without_tag.yml
- scripts/generate_xcframework.sh
由于 macos-14 上生成 visionOS 平台的 framework，报错 `visionOS 1.2 is not installed. To use with Xcode...`，暂且先忽略 visionOS 平台
> ci: ignore visionOS archive

- Package.swift
- Services/SwiftProtobuf/SwiftProtobuf.swift
https://github.com/apple/swift-protobuf/blob/ebc7251dd5b37f627c93698e4374084d98409633/Sources/SwiftProtobuf/Message%2BBinaryAdditions_Data.swift#L34
```swift
@inlinable
@available(*, deprecated, renamed: "init(serializedBytes:extensions:partial:options:)")
public init(
serializedData data: Data,
extensions: (any ExtensionMap)? = nil,
partial: Bool = false,
options: BinaryDecodingOptions = BinaryDecodingOptions()
) throws {
self.init()
try merge(serializedBytes: data, extensions: extensions, partial: partial, options: options)
}
```
https://github.com/apple/swift-protobuf/blob/ebc7251dd5b37f627c93698e4374084d98409633/Sources/SwiftProtobuf/SwiftProtobufContiguousBytes.swift#L57
```
extension Data: SwiftProtobufContiguousBytes {}
```
> fix: replace deprecated api from swift-protobuf

- .github/workflows/ci.yml
- Example/GrowingAnalyticsTests/HostApplicationTests/AutotrackerTests/Event/A3PageEventsTest.m
- Example/Podfile.lock
> build: ci runs on macos-15 runner image

- Example/Example/AppDelegate.m
- GrowingTrackerCore/GrowingTrackConfiguration.m
- Modules/Advertising/CAID/GrowingCAIDFetcher.h
- Modules/Advertising/CAID/GrowingCAIDFetcher.m
- Modules/Advertising/GrowingAdvertising.m
- Modules/Advertising/Public/GrowingAdvertising.h
支持广协 CAID 归因，需要在 SDK 初始化时，通过配置项 `configuration.CAIDFetchBlock` 传入获取 CAID 操作(需保证每次获取最新 CAID)，并在 block 最后调用 didCompleteBlock 传入获取到的 CAID JSON 字符串，示例如下：
```objc
configuration.CAIDFetchBlock = ^(void (^ _Nonnull didCompleteBlock)(NSString * _Nonnull)) {
// 模拟异步请求
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
NSString *caid =  @"["
@"{\"caid\":\"507b36cb169864220bc22a8c522532fa\",\"version\":\"20220111\"},"
@"{\"caid\":\"e18a100398425c5026591525e844f7a7\",\"version\":\"20230330\"}"
@"]";
didCompleteBlock(caid);
});
};
```
如果未调用 didCompleteBlock 或超时 5 秒，则此前生成的 ACTIVATE 事件将使用此前获取到的缓存在内存中的 CAID 事件属性(如果有)
> feat(ads): ANLSPI-22249 CAID support

- .github/workflows/spm.yml
- Example/Podfile.lock
- GrowingAutotrackerCore/GrowingNode/Category/UICollectionView+GrowingNode.m
- GrowingTrackerCore/Manager/GrowingSession.h
- GrowingTrackerCore/Manager/GrowingSession.m
- GrowingTrackerCore/Utils/GrowingDeviceInfo.h
- GrowingTrackerCore/Utils/GrowingDeviceInfo.m
- Modules/ABTesting/Request/GrowingABTRequest.m
* feat(ABTesting): 分流服务请求添加 newDevice 参数
* fix: deviceId Getter 方法添加双重锁，(1) 避免多线程环境下可能生成不同的 deviceId；(2) 性能优化
* fix(autotrack): 同步 4.5.0-hotfix.3 的修改，兼容更多的 CollectionView HeaderView 场景
> feat(ABTesting): ANLSPI-23827 new device

- Example/GrowingAnalyticsTests/TrackerCoreTests/SwizzleTests/GrowingSwizzleTest.m
- Example/Podfile.lock
- GrowingAnalytics.podspec
- GrowingAutotrackerCore/Autotrack/UICollectionView+GrowingAutotracker.m
- GrowingAutotrackerCore/Autotrack/UITableView+GrowingAutotracker.m
- Package.swift
+[GrowingULSwizzle realDelegate:toSelector:] 已于 GrowingUtils 1.2.4 版本废弃，具体见：
https://github.com/growingio/growingio-sdk-ios-utilities/pull/5
此 PR 移除该接口调用，并修复 CI 报错
> fix: ANLSPI-27507 remove using of deprecated api

- GrowingAutotracker/GrowingAutotracker.h
- GrowingAutotrackerCore/Autotrack/UIViewController+GrowingAutotracker.h
- GrowingAutotrackerCore/Autotrack/UIViewController+GrowingAutotracker.m
- GrowingAutotrackerCore/GrowingRealAutotracker.m
- GrowingAutotrackerCore/Page/GrowingPage.m
* 添加手动标识页面标题接口，请在 ViewDidAppear 生命周期之前调用：
```swift
[[GrowingAutotracker sharedInstance] setPageTitle:@"custom_title" forPage:self];
```
* 设置 nil 时，使用原标题
> feat: add setPageTitle api in autotracker

- .github/workflows/spm.yml
- GrowingAnalytics.podspec
- GrowingTrackerCore/Public/GrowingBaseEvent.h
- Modules/UniApp/GrowingUniAppPlugin.m
- Modules/UniApp/Public/GrowingUniAppPlugin.h
添加 uni-app 模块调用接口，用于 uts 插件集成，见：https://github.com/growingio/growing-sdk-uniapp/tree/op
> feat: uniapp track page event support #338
